version: '3.9'

name: recaptcha-service

services:

  #####################
  # RECAPTCHA SERVICE #
  #####################
  
  api:
    container_name: recaptcha-service-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: dev # Faster build times for local develpment, this will be automatically changed to release if omitted
    environment:
      ALWAYS_TRUE: ${RECAPTCHA_ALWAYS_TRUE:-true}

    ports:
      - "127.0.0.1:0:80"

volumes:
  db-data: